public class TryCatchExample1 {
    public static void main(String[] args) {
        try {
            int data = 50 / 0;
            System.out.println("Result: " + data); 
        } catch (ArithmeticException e) {
            System.out.println("An arithmetic exception occurred: " + e.getMessage());
        }
        System.out.println("Rest of the code");
    }
}








public class TryCatchExample9 {

    public static void main(String[] args) {
      try
	  {
      int arr[]= {1,3,5,7};
      System.out.println(arr[10]); 
       }
// handling the array exception 
    catch (ArrayIndexOutOfBoundsException e)
     {
     System.out.println(e);
     }
     System.out.println("rest of the code");
	 }
	 }






 
